### ISSUE TITLE
add read/write methods for waterlog events

### ISSUE THREAD

**Issue by dyf** [AllenNeuralDynamics/aind-slims-api#1]
Add two methods:
1. a method to write waterlog events to SLIMS
2. a method to read waterlog events from SLIMS, given a mouse identifier

Also, add a simple class to handle authentication from configuration/settings with a [slims-python-api](https://github.com/genohm/slims-python-api) session, like this: https://github.com/AllenNeuralDynamics/aind-metadata-service/blob/84815d0571ee31eaa3c3fa3f3ecc8dd6a050266b/src/aind_metadata_service/slims/client.py#L21

**Comment by mochic** [comment]
Resolved here: https://github.com/AllenNeuralDynamics/aind-slims-api/pull/23
